name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  static-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --filter frontend

      - name: Build static files
        run: pnpm --filter frontend build

      - name: Deploy documentation to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
        run: aws s3 sync ./frontend/dist s3://skkuzzim.com

  api-build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/skkuzzim:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  api-deploy:
    needs: api-build-image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.AWS_SSH_KEY }}
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          script: |
            echo "${{ secrets.ENV_FILE }}" > .env
            docker-compose down 
            docker-compose pull 
            docker-compose up -d
